### ISSUE TITLE
Other jar files with different filenames

### ISSUE THREAD

**Issue by martindb** [wmanth/vscode-jar-viewer#13]
Hi! Is there any way (without modifing the vscode extension) to add support for *.aar files?
I work with those .aar files (webservices) that are jar files, in practice, if I rename the files to .jar your extension works great.

**Comment by kaushik-revefi** [comment]
I would like the same for "srcjar" extension which is essentially a jar file. Currently, I rename srcjar into jar and this jar-viewer works perfectly good with it.
